apiVersion: v1
kind: Service
metadata:
  labels:
    app: java
  name: ks-sample-java
  namespace: kubesphere-sample-dev
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31861
  selector:
    app: java
    
    tier: backend
  sessionAffinity: None
  type: NodePort
